<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Forecast Marketing</name>
   <tag></tag>
   <elementGuidId>99022372-dc19-4deb-b37a-c188ec256b9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f5e71bc-9e42-4d12-ae1b-aa7b6db7f17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>8d241886-1781-4607-b76f-4e2e51910498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Forecast Marketing</value>
      <webElementGuid>6b8480e2-2e7b-40e6-8f98-7fa701fd40ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;c-app&quot;]/div[@class=&quot;c-wrapper c-fixed-components&quot;]/div[@class=&quot;c-body&quot;]/main[@class=&quot;c-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;fade-in&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;card-header&quot;]</value>
      <webElementGuid>1d3b1b4f-93da-49c7-a3ad-f8ab21ba2876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/div/div/div</value>
      <webElementGuid>a4003ab3-7f1a-4b68-84ee-2a6f619df6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Forecast Marketing' or . = ' Forecast Marketing')]</value>
      <webElementGuid>6daef6d4-fde6-4ad3-8115-f00efaccf6b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
