<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Budi Santoso - Budi Santoso (CUST-  1880)</name>
   <tag></tag>
   <elementGuidId>a009d862-7904-4f81-b1ba-cb09e9c76984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-store-wz-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-store-wz-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9ad3bd2a-fe83-448e-ac2d-f4553b2dd5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>431253f8-3e1a-4122-a01e-fcbe483973f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-store-wz-container</value>
      <webElementGuid>dbdb156e-47e1-4f43-b025-94239976302b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c7059e52-790d-4fb2-8338-60c81e74ba64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22e2cb11-a4b0-4e68-85fe-b8d49a2fde10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Budi Santoso - Budi Santoso (CUST-  1880)</value>
      <webElementGuid>514298ff-5734-499a-b778-919248eaee1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Budi Santoso - Budi Santoso (CUST-  1880)</value>
      <webElementGuid>a35e9fa1-8809-4392-849c-17904b03ec6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-store-wz-container&quot;)</value>
      <webElementGuid>a7a9583c-fa86-4697-9d1c-890a5ee5e79d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-store-wz-container']</value>
      <webElementGuid>aab6e3a6-cac6-4668-bd89-294eae5af808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-forecast-marketing-add']/div[3]/div/div/div/div/div/span/span/span/span</value>
      <webElementGuid>8131b53e-4e5b-4737-9520-a0ae1a6b53fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[4]</value>
      <webElementGuid>9d44c793-eab4-429d-8d57-81c6c4970d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forecast sudah terisi'])[1]/preceding::span[4]</value>
      <webElementGuid>58567a11-5229-486e-969f-26d85edceeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/span/span/span/span</value>
      <webElementGuid>c3a076e2-2dcd-4827-a366-bcad417df529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-store-wz-container' and @title = 'Budi Santoso - Budi Santoso (CUST-  1880)' and (text() = '×Budi Santoso - Budi Santoso (CUST-  1880)' or . = '×Budi Santoso - Budi Santoso (CUST-  1880)')]</value>
      <webElementGuid>cf826156-0bf3-45ef-8ede-e79ab2b1574e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
