<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Toko</name>
   <tag></tag>
   <elementGuidId>e85295bd-62af-4cbe-8c08-5df1dd8013c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-store-wz-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-store-wz-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>63d74563-8cf5-44c8-a484-1c10eb20aae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>08234059-a460-4e95-9ed0-b32d3e9bbb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-store-wz-container</value>
      <webElementGuid>9acb8195-9dea-4ad3-9c6d-bd0d7b775723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1016bf35-2329-43a5-bd54-3fb3e97d5146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a33d61ff-23de-4c37-aa12-8cc7af74b3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toko </value>
      <webElementGuid>bf29133f-c748-4327-8259-b0385c1fbfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-store-wz-container&quot;)</value>
      <webElementGuid>07cb5167-6b8d-4d7c-b588-9d109aa3d403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-store-wz-container']</value>
      <webElementGuid>885f8c19-f2d5-49a2-a133-7117d768e406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-forecast-marketing-add']/div[3]/div/div/div/div/div/span/span/span/span</value>
      <webElementGuid>78f7b0a9-ea5a-4457-8af2-900f792c6fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[4]</value>
      <webElementGuid>31b9ba57-f26b-4467-a3a8-02951a715c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak Boleh Kosong'])[1]/preceding::span[4]</value>
      <webElementGuid>f050dc41-e13d-4b62-8dea-b971c35c0577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/span/span/span/span</value>
      <webElementGuid>0ff0d701-2af4-4629-a0ab-e4d17d1bea4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-store-wz-container' and (text() = 'Toko ' or . = 'Toko ')]</value>
      <webElementGuid>85037934-3652-4432-b7fd-e1f1d3d34eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-store-io-container']</value>
      <webElementGuid>ea35b2d6-e47d-49de-b4dd-a9e91ce4dcd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-store-io-container' and (text() = 'Toko ' or . = 'Toko ')]</value>
      <webElementGuid>114fcc16-e489-4f9c-b31d-afa6b695e0e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
