<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah Lampiran</name>
   <tag></tag>
   <elementGuidId>46a631c2-98dc-4791-bf87-0b3ee1286c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unggah-to-dealer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='unggah-to-dealer']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'unggah-to-dealer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a06fbaf1-5781-4674-8980-dbad8891fd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary button-unggah btn-lg float-right</value>
      <webElementGuid>0702cfd0-e3d2-4830-96d5-81bebdbc68dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94312d65-2781-47bd-8894-4018d90d591e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unggah-to-dealer</value>
      <webElementGuid>642c346e-19ed-4352-92e3-d6c984cbc16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah Lampiran</value>
      <webElementGuid>2e9bd83b-6731-461d-a148-234cadd558cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unggah-to-dealer&quot;)</value>
      <webElementGuid>498982f2-e669-410a-9ce2-0d81853a2181</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='unggah-to-dealer']</value>
      <webElementGuid>1ef037fc-6976-43cf-b59d-5141e598772c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-registrasi-kios-to-subdealer']/div[2]/button[2]</value>
      <webElementGuid>9bdcef20-3ba8-4a08-a558-373171033791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrasikan'])[1]/following::button[1]</value>
      <webElementGuid>36358128-abb6-426a-a3c4-ceeef2816d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Distributor'])[2]/following::button[2]</value>
      <webElementGuid>65fcb939-a671-46f0-ae8b-c50fc3e7cea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran Pengajuan Sub-Dealer'])[2]/preceding::button[1]</value>
      <webElementGuid>2dc02bde-49c8-478a-93f9-c919ff520094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran'])[1]/preceding::button[1]</value>
      <webElementGuid>4000df35-bb63-4c29-a975-4fdf53e79ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button[2]</value>
      <webElementGuid>412caa47-ad5e-4eb2-9a57-d3fd91bc1e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'unggah-to-dealer' and (text() = 'Unggah Lampiran' or . = 'Unggah Lampiran')]</value>
      <webElementGuid>a1bc7132-19a1-4346-84dd-e1a7f48422af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-registrasi-kios-to-dealer']/div[2]/button[2]</value>
      <webElementGuid>f3f967d1-89c2-4a21-8420-54fbb0abe271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atas Nama'])[2]/following::button[2]</value>
      <webElementGuid>a9572acf-495b-450f-8d22-ea3123410d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran Pengajuan Dealer'])[2]/preceding::button[1]</value>
      <webElementGuid>1dc9ee89-79a8-4104-bba7-185bfb8582a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
