<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batal</name>
   <tag></tag>
   <elementGuidId>49e5b047-0ed6-40a0-9581-a76f2ef204e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#batalUploadDealer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='batalUploadDealer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80f4776c-3c14-456a-94f8-20815025f39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary button-reset mb-2</value>
      <webElementGuid>fe0703d1-7cfe-4b71-bccd-32e907afa701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>067e13fd-94c3-4dd5-b64e-77f342ff5307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>batalUploadDealer</value>
      <webElementGuid>3be83547-419f-458e-a89f-2d9228ea1f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batal</value>
      <webElementGuid>a56a0927-a07a-40ea-9e6e-fe4d6bf748d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;batalUploadDealer&quot;)</value>
      <webElementGuid>1ec6212b-eac9-467b-9808-138fd9820713</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='batalUploadDealer']</value>
      <webElementGuid>4b198f53-f57f-4f63-9172-cce1198da958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-lampiran-tokios-dealer']/div/div[4]/button</value>
      <webElementGuid>dd1eff2b-5e6f-4453-9802-0b565ee66432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lain-lain'])[1]/following::button[1]</value>
      <webElementGuid>b0e3070d-980c-447f-8223-a02bc695eb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto Sub-Dealer (WAJIB)'])[2]/following::button[1]</value>
      <webElementGuid>517cb82a-ae9e-4919-8246-604f5a25dd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[1]/preceding::button[1]</value>
      <webElementGuid>f5568e23-5c99-4750-8aa0-55a2ee42f605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrasi Kios To Sub-Dealer'])[1]/preceding::button[2]</value>
      <webElementGuid>82ccbc0f-7e37-48ff-af97-c75b70b5bbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/button</value>
      <webElementGuid>2e17eab0-7848-4a86-be7e-28d2fb52e5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'batalUploadDealer' and (text() = 'Batal' or . = 'Batal')]</value>
      <webElementGuid>0e9bc579-3b52-441c-8e67-3e8f9f00fa95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
