<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Petani Kunci</name>
   <tag></tag>
   <elementGuidId>50bf313d-4f17-4a8a-aaaf-357e28d9c710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='ButtonTambahPetaniKunci'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table_daftar_petani_kunci > div.header-petanikunci > div.row > div.col > #ButtonTambahPetaniKunci</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04645360-21b2-4de7-91b8-dfb9bcecca87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ButtonTambahPetaniKunci</value>
      <webElementGuid>c1fb7c42-6d7c-4f7e-95ea-4f5bda5b727b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>121a382b-61d4-4c6f-b05b-128a02a9be74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-add-petani-kunci</value>
      <webElementGuid>1796f9c2-9138-4f92-8752-161e5e38d1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah Petani Kunci </value>
      <webElementGuid>74b0d9e4-d3de-4f16-84ba-92074d105666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_daftar_petani_kunci&quot;)/div[@class=&quot;header-petanikunci&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/button[@id=&quot;ButtonTambahPetaniKunci&quot;]</value>
      <webElementGuid>522d3f28-41cc-4097-805e-821be0f9d84d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='ButtonTambahPetaniKunci'])[2]</value>
      <webElementGuid>0c8a45f7-71cf-4ee3-8cac-872e45276908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table_daftar_petani_kunci']/div/div/div[2]/button</value>
      <webElementGuid>1f6d00f7-20d1-4575-b47c-eaac09ffa7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Petani Kios'])[2]/following::button[1]</value>
      <webElementGuid>860619b4-acce-423a-aef5-34b59379fea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan Data Kios'])[1]/following::button[1]</value>
      <webElementGuid>74fb1301-dfbd-46b0-b9d4-76d8b094b853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Petani'])[2]/preceding::button[1]</value>
      <webElementGuid>f57eac35-c24e-43c7-8ba1-e639b728dbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[6]/preceding::button[1]</value>
      <webElementGuid>235dfb73-19e0-4d7e-a098-04b247748376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/div/div/div[2]/div/div/div/div[2]/button</value>
      <webElementGuid>e5e5bddc-f3d4-46f4-9159-fcfd18f1c042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ButtonTambahPetaniKunci' and @type = 'button' and (text() = ' Tambah Petani Kunci ' or . = ' Tambah Petani Kunci ')]</value>
      <webElementGuid>d41f3039-3a5b-431e-b8e4-3d3396b730d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
