<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Registrasikan</name>
   <tag></tag>
   <elementGuidId>8ce7c4fe-62d3-46e8-b040-8430032151d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button_unggah_lampiran</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_unggah_lampiran']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d92eca82-7721-4b0c-bceb-ae501bb22563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_unggah_lampiran</value>
      <webElementGuid>912c6ce7-8b58-4d1c-9dd6-6aedcbf3bca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary button-unggah unggah-costume-color</value>
      <webElementGuid>342ac5af-ab24-44d8-ba0a-db7811ece550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>636c550e-5a42-4924-b0bf-9ef4b168d54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registrasikan</value>
      <webElementGuid>5d3ba24f-996a-49aa-afce-32b10c16d752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_unggah_lampiran&quot;)</value>
      <webElementGuid>15d55af1-19e5-49ed-b0b1-dc0ea4ca4f8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_unggah_lampiran']</value>
      <webElementGuid>957a54ea-9159-4930-95fb-e8ef8c6fffd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-registrasi-kios-to-subdealer']/div[2]/button</value>
      <webElementGuid>25a2e286-da57-44a4-b230-b8bf4315aeac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Distributor'])[2]/following::button[1]</value>
      <webElementGuid>aa60ddf1-ccf6-4202-8593-776be7855078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distributor'])[1]/following::button[1]</value>
      <webElementGuid>b83223a6-06ef-4cae-b1bd-8c08e5d7401c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Lampiran'])[2]/preceding::button[1]</value>
      <webElementGuid>b059adc5-d068-4561-82f2-abbf07b476a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran Pengajuan Sub-Dealer'])[2]/preceding::button[2]</value>
      <webElementGuid>dfee1b98-4fe6-40eb-8cb6-811eb0cff1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registrasikan']/parent::*</value>
      <webElementGuid>fef1ab9f-56dd-4977-9b68-87a16848bdbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>393047db-ea62-4e32-a5ca-8bdb9c38c4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button_unggah_lampiran' and @type = 'button' and (text() = 'Registrasikan' or . = 'Registrasikan')]</value>
      <webElementGuid>c2fe84b6-5109-44c3-b2cb-2ea373fb7a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-registrasi-kios-to-dealer']/div[2]/button</value>
      <webElementGuid>14be7a86-b54b-4e10-be4b-27b2a3214241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atas Nama'])[2]/following::button[1]</value>
      <webElementGuid>c65dac92-2777-43ca-8f4d-633bb5c84891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Rekening'])[2]/following::button[1]</value>
      <webElementGuid>8e3a55cd-8d7d-42ca-8a4b-25b43ce8f600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran Pengajuan Dealer'])[2]/preceding::button[2]</value>
      <webElementGuid>e46832d8-8c3f-4f95-b0fe-d4f6cdaa0ea8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
