<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ya - registrasi sub dealer</name>
   <tag></tag>
   <elementGuidId>77933d5f-a5d4-4abc-b7dd-ca61569e1638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[36]/div/div/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmitButtonModalAgree</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'btn button-modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-modal</value>
      <webElementGuid>7032ac24-8ecf-4d47-960a-207d001c2525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>def0a82c-b8b5-466b-9044-9b08b42c24e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a0f544b4-4a53-4b31-9fa4-e4490aa04ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmitButtonModalAgree</value>
      <webElementGuid>d6353335-f1a2-421f-8aeb-cac9b2d75cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>dae56392-cf7d-4760-ab35-3b0c19c19117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>04d2d6c4-c3ce-4399-9fd0-5462f2283ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ya </value>
      <webElementGuid>7da5868d-9e41-4b28-9397-cb95d6e4edfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;c-app modal-open&quot;]/div[@id=&quot;modal-simpan-save&quot;]/div[@class=&quot;modal-dialog modal-confirmation&quot;]/div[@class=&quot;modal-content add&quot;]/div[@class=&quot;modal-footer&quot;]/button[@id=&quot;SubmitButtonModalAgree&quot;]</value>
      <webElementGuid>a6694bbe-55e5-4cf4-9c37-058343cdc43d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='SubmitButtonModalAgree']</value>
      <webElementGuid>01210ead-cdc2-46b5-8d7a-caa75e564462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-simpan-save']/div/div/div[2]/button[2]</value>
      <webElementGuid>5762f148-b4f7-4f1f-be91-cd01f5a136d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[31]/following::button[1]</value>
      <webElementGuid>7e86706b-d734-4af4-bd4b-1f09479b67a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Data akan terkunci. Pastikan data sudah Benar'])[1]/following::button[2]</value>
      <webElementGuid>684f120e-db39-4ba7-9d50-808dbdd39e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda yakin ingin membatalkan ??'])[1]/preceding::button[1]</value>
      <webElementGuid>1946231e-895c-4c46-a75f-7c1c6620b52c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Data yang Anda isikan di form akan terhapus'])[1]/preceding::button[1]</value>
      <webElementGuid>81c643be-8357-4907-9654-fa577e6b441b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[36]/div/div/div[2]/button[2]</value>
      <webElementGuid>9f7d0ff4-99d8-422a-b897-8dc1b7d9178f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'SubmitButtonModalAgree' and (text() = ' Ya ' or . = ' Ya ')]</value>
      <webElementGuid>3c74657f-72ab-423a-a047-72fc60390684</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
