<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah</name>
   <tag></tag>
   <elementGuidId>6f2729e3-b8d0-46f9-b394-bb381be80ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ButtonUnggah-lampiran</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ButtonUnggah-lampiran']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46efd201-6ab9-4c59-b0e6-0802bed276b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ButtonUnggah-lampiran</value>
      <webElementGuid>28b0fbba-f985-407c-997c-d248f5ab9f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary button-unggah</value>
      <webElementGuid>daa65a6d-702f-4711-9307-ffdd73aa5209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Unggah </value>
      <webElementGuid>740070f4-54f6-40a2-9544-7b517446e915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ButtonUnggah-lampiran&quot;)</value>
      <webElementGuid>e9917ac7-8963-4117-a227-cd8f57c7cbc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ButtonUnggah-lampiran']</value>
      <webElementGuid>22e44e25-88fa-4ed2-8d63-aaf0fddc6b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-lampiran-tokios-dealer']/div/div[4]/button[2]</value>
      <webElementGuid>7237878c-7a00-400a-a419-9ba363403296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[41]/following::button[1]</value>
      <webElementGuid>a1f91c8f-888f-496c-bb67-8c9adb3145dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove file'])[1]/following::button[2]</value>
      <webElementGuid>3d1c3635-a992-4426-b63b-caf00db4a842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrasi Kios To Sub-Dealer'])[1]/preceding::button[1]</value>
      <webElementGuid>8e33684b-350e-4167-8206-90872287c155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identitas Pemilik'])[1]/preceding::button[1]</value>
      <webElementGuid>0c3129e8-a7c1-4409-8401-6c5fbe7d22c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unggah']/parent::*</value>
      <webElementGuid>a474738d-700a-4105-9100-60b546f93537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>e71bb7a5-2c8b-4a32-a1d8-2e3d7e2f9519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ButtonUnggah-lampiran' and (text() = ' Unggah ' or . = ' Unggah ')]</value>
      <webElementGuid>5c4b1c1b-1dca-4e52-9718-a5bbe6613f4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
