<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ajukan</name>
   <tag></tag>
   <elementGuidId>2267baa0-6205-4165-b334-a75eeb09c53f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SubmitButton-ajukan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='SubmitButton-ajukan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9c3d9fa-70b2-4ebc-8fc2-3082aadb186f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmitButton-ajukan</value>
      <webElementGuid>1be8b77d-aec9-459a-8934-34683254d7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-ajukan btn-sm</value>
      <webElementGuid>ad837a8b-281c-4fcd-9e4b-1b7c4da79ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a05f221e-86d4-4fef-a9ae-00239feaece6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>d895f44d-011f-41fb-b3e0-52fe170b670f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-add</value>
      <webElementGuid>de976733-418c-49bd-8e76-8109d49a5c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajukan </value>
      <webElementGuid>69002fd7-7839-4bd9-9502-84e9facaed0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmitButton-ajukan&quot;)</value>
      <webElementGuid>bfca18d2-f34b-4288-93a2-80d7cbe3506e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='SubmitButton-ajukan']</value>
      <webElementGuid>54d39826-bbcc-4762-980f-ee61ca71d937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='unggahan-file-document']/div/div[2]/button[2]</value>
      <webElementGuid>41fffbfa-443a-4329-b641-3dff352628d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[42]/following::button[1]</value>
      <webElementGuid>9b560a24-1f88-411c-9baa-5e6d12551d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/following::button[2]</value>
      <webElementGuid>bf6c0fba-3611-45a0-89bc-72619aab7b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda sudah yakin dengan data tersebut?'])[8]/preceding::button[1]</value>
      <webElementGuid>26f58f2a-9d92-4730-8dee-68a13b565317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[43]/preceding::button[1]</value>
      <webElementGuid>1388d238-cd12-4772-83ab-a8baf4edab0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ajukan']/parent::*</value>
      <webElementGuid>c020b0fb-55e8-47f9-a2b4-bac7417fea2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/button[2]</value>
      <webElementGuid>5e885fbe-ee4c-49b9-948a-f3475b87a1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'SubmitButton-ajukan' and @type = 'button' and (text() = 'Ajukan ' or . = 'Ajukan ')]</value>
      <webElementGuid>12033307-3728-455d-ac18-60227c160d36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
