<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Atas Nama_owner_bank_dealer</name>
   <tag></tag>
   <elementGuidId>f24089dc-8f05-47ff-938b-92abf05edd41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='owner_bank_dealer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#owner_bank_dealer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d01f560c-64b2-4269-a7c3-ce1b2afa5c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>owner_bank_dealer</value>
      <webElementGuid>ae6a0a7f-6271-47ed-ae36-f8b73314d60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2db4ef0c-7088-4ea8-8695-e5325b4e7a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d39a462c-2c9f-4295-88b2-0e76a93fa5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>owner_bank_dealer</value>
      <webElementGuid>578ef322-52ef-421c-919c-dd3a37a2df0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Pemilik Rekening</value>
      <webElementGuid>eec2d8e1-ac6f-4fe7-9dfa-b247dd1042db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;owner_bank_dealer&quot;)</value>
      <webElementGuid>c8cfc77b-ea09-4c55-9cae-85d21a7f787b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='owner_bank_dealer']</value>
      <webElementGuid>315577b0-7fd8-41ab-ae18-e8ff8a569fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-dealer']/div[11]/input</value>
      <webElementGuid>bc4ab231-49c4-42a6-b5e7-48fb04159e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[11]/input</value>
      <webElementGuid>ced3279b-10d0-4eec-bec6-558ac5094206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'owner_bank_dealer' and @type = 'text' and @name = 'owner_bank_dealer' and @placeholder = 'Nama Pemilik Rekening']</value>
      <webElementGuid>89aec8c6-d877-4d8b-afab-ffd6792cbe9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
