<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Atas Nama_owner_bank</name>
   <tag></tag>
   <elementGuidId>749ba6bc-d04f-4ef1-93d4-c6f9962dee0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='owner_bank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#owner_bank</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81bdbca7-93cf-429a-8d35-0652ac30e134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>owner_bank</value>
      <webElementGuid>5352c318-b30d-4197-a4f5-4ae3f7429618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5419fcef-1ac8-40e9-93ff-7f187d5a56dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3eeda9ee-8880-462d-b2a3-f4c97db8605f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>owner_bank</value>
      <webElementGuid>6b958423-922c-4f52-a2b5-4bc6a9c7b952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Pemilik Rekening</value>
      <webElementGuid>5de878e9-8e6d-44e8-bd13-7a0a6214070d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;owner_bank&quot;)</value>
      <webElementGuid>903fa232-824c-437c-8ea3-b2258aab0b85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='owner_bank']</value>
      <webElementGuid>e32a250e-8ab2-4925-aa57-045d0d110c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-pemilik']/div[11]/input</value>
      <webElementGuid>f8660615-909a-4755-9dda-c21a3136989c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>8e67e535-ac07-444b-8ff8-35e8890912e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'owner_bank' and @type = 'text' and @name = 'owner_bank' and @placeholder = 'Nama Pemilik Rekening']</value>
      <webElementGuid>dd7afb9c-72bb-4e35-aea7-152a4afd8e9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
