<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__owner_ktp</name>
   <tag></tag>
   <elementGuidId>d7369ebf-fa52-4e84-8990-58e14009af57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;owner_ktp&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='owner_ktp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>450d79a0-2297-4be1-9112-4396c8617cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c71051cb-a449-4040-afd8-81cf7f7264fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control btn-remove-disabled-agree</value>
      <webElementGuid>f9154321-d372-4414-beb5-ebbf776c8a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mask</name>
      <type>Main</type>
      <value>0000000000000000</value>
      <webElementGuid>b2d04b86-af44-49cf-a63a-6a6aea7a47c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>owner_ktp</value>
      <webElementGuid>96e477f0-bd4d-4e17-8d07-b9aa9d4d4c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. KTP</value>
      <webElementGuid>fcf1e1ba-1bdc-4161-902e-612a43517007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bde612fe-1af8-4775-967b-cc4c04a61b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>f6979e26-7b94-44ac-831b-5aa25cfae792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b57d081b-bd2a-4c99-9828-fe880bbb96b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identitas-pemilik&quot;)/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control btn-remove-disabled-agree&quot;]</value>
      <webElementGuid>32437151-dd41-451f-af41-4e8372b05638</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='owner_ktp']</value>
      <webElementGuid>6b195c1e-be0b-45cd-a63e-ff2773d5a5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-pemilik']/div[7]/input</value>
      <webElementGuid>b446ea24-675f-42ae-b765-24a207970a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>795c88c8-b480-4ccd-a331-4db73cc7af0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'owner_ktp' and @placeholder = 'No. KTP']</value>
      <webElementGuid>5bf53c91-10c0-400e-af0a-fce2d2d2ee5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
