<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kios_gmaps</name>
   <tag></tag>
   <elementGuidId>fc4ed7f6-9952-48d0-a280-80c5afdc9722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kios_gmaps']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kios_gmaps</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0462639f-7ebf-4c0b-8b9c-49efc1dba67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2be8fd0b-b62a-4b0e-933c-2ce02550030c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kios_gmaps</value>
      <webElementGuid>36695943-1178-4286-a24a-fb409aa0c558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kios_gmaps</value>
      <webElementGuid>2d929244-0ea8-4220-bc96-2d5f4d80db29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Link GMaps</value>
      <webElementGuid>baa0513b-3b0d-4426-a1b9-b106e7e4963c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d798c7db-da98-4753-ad2e-85e77c981973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85b8482e-1851-40d1-9c60-f3918bf01c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kios_gmaps&quot;)</value>
      <webElementGuid>67b97409-056c-437b-8b08-204ef5995f11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kios_gmaps']</value>
      <webElementGuid>1289e9dd-e565-401b-942b-4949887b6b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='tambah-kios']/div/div[2]/div[4]/div/input</value>
      <webElementGuid>a5c6c7b4-2e31-4283-b125-e16b7b6c3c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>181cfff9-f586-4f8d-b0c9-06300c47bfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'kios_gmaps' and @name = 'kios_gmaps' and @placeholder = 'Link GMaps' and @type = 'text']</value>
      <webElementGuid>ec68d22c-eb3d-434e-bfa1-29ffa71197ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
