<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__owner_telephone</name>
   <tag></tag>
   <elementGuidId>109ca2f5-0e11-4cdf-b0f9-72b70ef6d0a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;owner_telephone&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='owner_telephone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36a3676d-415f-4561-a004-34b3fd516629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7bd9ae48-ca39-4468-8b7e-25a5a8b2f5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control btn-remove-disabled-agree</value>
      <webElementGuid>6d590d33-dfda-4b23-a347-d86cbb43d68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>owner_telephone</value>
      <webElementGuid>f40a7b5d-e2d3-4ab7-9e5e-6ec182124cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>3d3feb33-1b86-4582-976c-5f6fa99b462b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^0-9]/g, '').replace(/^0+/, '')</value>
      <webElementGuid>524b32b8-3d68-4f4b-920c-e01f94fcb385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. Telp</value>
      <webElementGuid>357d5574-d314-4409-bbf4-380054c1dd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5fbd182-04bc-4d4a-aeed-e443b5f5abc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identitas-pemilik&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group telphone&quot;]/input[@class=&quot;form-control btn-remove-disabled-agree&quot;]</value>
      <webElementGuid>ea2af73c-b170-4fdc-8518-fc4d4bd6c01f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='owner_telephone']</value>
      <webElementGuid>17fc03b5-9f2b-408f-b957-ea100b0551e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-pemilik']/div[9]/div/input</value>
      <webElementGuid>ac05b660-98d5-4e2e-b565-0c39f2c8731d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>f0871fc2-4d94-4ef8-b56b-1b8c1218aed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'owner_telephone' and @placeholder = 'No. Telp']</value>
      <webElementGuid>82c18d37-b457-439a-b795-84eab8e099fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
