<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__checkbox</name>
   <tag></tag>
   <elementGuidId>ca898bef-d6e1-48b6-9c72-33f9a454d4bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flexCheckDefault2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flexCheckDefault2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c25f2e6-e95d-4736-95e2-5e5e78f40a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>b03d7138-2f06-458a-8ea7-2af59895ab61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c49f8bcc-2fef-4ada-99b2-c89e85b5bc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkbox[]</value>
      <webElementGuid>38908fa4-cb04-468d-b273-2523e6e450ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexCheckDefault2</value>
      <webElementGuid>5641dc8b-ba53-40ec-97b5-5db5eab79f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flexCheckDefault2&quot;)</value>
      <webElementGuid>866fc265-3520-45d3-ba9f-e6ddbbe45d97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flexCheckDefault2']</value>
      <webElementGuid>9f38e149-2891-4754-a0d4-e9069d728e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainList']/div[2]/input</value>
      <webElementGuid>d86ce39f-16e8-4d4f-a25e-d57b8f38779a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/form/div/div/div[2]/input</value>
      <webElementGuid>a88f55e0-1ff8-42e0-9a77-b36532caccdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkbox[]' and @id = 'flexCheckDefault2']</value>
      <webElementGuid>88f15bea-e563-46a8-b0ba-22e939c79f01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
