<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Rekening_no_rek_bank_dealer</name>
   <tag></tag>
   <elementGuidId>7176d4ac-6ee8-451d-8a4f-5f47b98dd480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_rek_bank_dealer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#no_rek_bank_dealer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1baa220-636d-47fe-9916-ac12f21e11f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c652980-34cd-49e5-a70d-1afb3d199527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6fc190e9-f66e-4199-bbf7-b46ce94e9810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mask</name>
      <type>Main</type>
      <value>0000000000000000</value>
      <webElementGuid>2bae73f0-edb0-437d-b95b-789a4eb5951f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_rek_bank_dealer</value>
      <webElementGuid>1077fd2d-35b1-472f-a53e-413163f52364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_rek_bank_dealer</value>
      <webElementGuid>dab5376b-70ee-4b64-af78-6d658d777aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Rekening</value>
      <webElementGuid>58d5e7ef-dff3-4fe3-8188-9ac7be24f300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5224c135-3af8-4286-b5d8-c34e4f6b4691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>d19adc07-a911-4d0f-be35-0a4ee012c43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_rek_bank_dealer&quot;)</value>
      <webElementGuid>8c4aafc3-0510-4996-8621-b93ee2567759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_rek_bank_dealer']</value>
      <webElementGuid>ef631f44-4222-451b-8906-82d68fd66ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-dealer']/div[10]/div[2]/input</value>
      <webElementGuid>80491cb5-a367-4064-8e8f-54a3e55ec2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[10]/div[2]/input</value>
      <webElementGuid>543dab39-4da5-4e53-802b-051288341aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'no_rek_bank_dealer' and @id = 'no_rek_bank_dealer' and @placeholder = 'Nomor Rekening']</value>
      <webElementGuid>96db1fa7-2a21-4343-acf6-207abd8683fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
