<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__owner</name>
   <tag></tag>
   <elementGuidId>1e48ae27-269e-4dcb-89a3-5080311e79e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#owner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='owner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73f79a72-d130-43eb-ba37-10d88e804799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>owner</value>
      <webElementGuid>8654d136-0e11-404d-9519-d869a2ed5dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00095ca0-c55f-48d0-8234-93dfa064caae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control btn-remove-disabled-agree one</value>
      <webElementGuid>c434d95a-79d0-4647-abe0-a92db8eab8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>owner</value>
      <webElementGuid>18a26432-a41e-4f07-b8eb-7a6f848f49c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Pemilik</value>
      <webElementGuid>1f14ed1f-6d5b-4f69-a03f-8801841d56fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56efa25f-5874-44b2-af2c-68215514ef9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;owner&quot;)</value>
      <webElementGuid>8aab1170-fde8-4425-a945-82cdf8c15eb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='owner']</value>
      <webElementGuid>56d9f923-4818-43bc-92ad-23b202957436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-pemilik']/div[2]/input</value>
      <webElementGuid>de613ee6-efa2-40ad-aad2-62d23a044eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/input</value>
      <webElementGuid>d2a6d651-a204-40ea-a61a-0bfd92143b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'owner' and @type = 'text' and @name = 'owner' and @placeholder = 'Nama Pemilik']</value>
      <webElementGuid>37376d8e-37dd-43df-8186-fa1900ed76e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
