<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kios_telp</name>
   <tag></tag>
   <elementGuidId>5135f664-023d-499e-a9c4-52a459444c03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kios_telp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kios_telp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7552472-7847-43d1-b6cb-de4f6361f055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kios_telp</value>
      <webElementGuid>0e3f5cc6-f054-4cc4-8ba9-f4a8a229c2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>86717ea8-9abb-4651-86b6-a54b33e637d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kios_telp</value>
      <webElementGuid>b5676fa9-82c3-4c57-96d3-e8614b7154bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis No. Telepon</value>
      <webElementGuid>5e471ef8-89b0-4bf4-befc-a19a83bec94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^0-9]/g, '').replace(/^0+/, '')</value>
      <webElementGuid>e4c503b5-1d5f-422f-8d50-8d8a80367018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b78b5b6d-7dd3-40dc-b047-e951c3070e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3c7eb67-658b-4938-ac67-bf46d36ff348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kios_telp&quot;)</value>
      <webElementGuid>133aa0d8-7ccb-4e46-9b70-5902f141b070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kios_telp']</value>
      <webElementGuid>fb031391-495d-4a60-8c99-b65a1f1a5bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='tambah-kios']/div/div/div[2]/div/input</value>
      <webElementGuid>25b4026a-75ad-4fa5-82b6-96b27d26e8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div[2]/div/input</value>
      <webElementGuid>10498694-9915-4a6d-9845-88e75d972090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'kios_telp' and @name = 'kios_telp' and @placeholder = 'Tulis No. Telepon' and @type = 'text']</value>
      <webElementGuid>d053abfa-45b7-4f26-a892-36e2c6638633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
