<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hapus_checkbox</name>
   <tag></tag>
   <elementGuidId>6dc88fe1-ef64-4a01-b551-0ff671f6a871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flexCheckDefault1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flexCheckDefault1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c705dfea-3280-4f4d-96b9-d2dad0e7fd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e428212a-fc81-4dd3-b0a6-8d43debad050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>908d03c5-ee4b-4bbb-83d4-345e531e2fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkbox[]</value>
      <webElementGuid>6d43a997-a9e8-43a7-a85f-2fe8e90323bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexCheckDefault1</value>
      <webElementGuid>fb27d397-6631-406e-9fd9-bd30c864c3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flexCheckDefault1&quot;)</value>
      <webElementGuid>8020ccf4-5d53-40af-8b6b-7bfff089fbab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flexCheckDefault1']</value>
      <webElementGuid>6361d41a-4bf1-47f4-9c90-7f113349d938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainList']/div/input</value>
      <webElementGuid>b055f789-68cf-4acd-9262-2e9fb2b0482c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/form/div/div/div/input</value>
      <webElementGuid>038dc0ec-c906-46f8-8398-9336b1f76f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkbox[]' and @id = 'flexCheckDefault1']</value>
      <webElementGuid>fcdc95fb-77f3-4212-a0ce-7bf7603eed8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
