<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kios_nama</name>
   <tag></tag>
   <elementGuidId>c067e253-c003-4f97-b6c9-e0bb3914dc84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kios_nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kios_nama</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8954d498-79b5-4c42-9ab2-6449b3b91568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kios_nama</value>
      <webElementGuid>de5d524e-720c-42e7-bf02-d412c12f2f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aabe7725-8439-4283-8240-629b9f519793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kios_nama</value>
      <webElementGuid>238267dd-f566-4a20-8789-73e7b83ecf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Nama Kios</value>
      <webElementGuid>3e025ae8-ea20-49e1-95a0-8c45a9de705c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f05e3dbf-f85b-484f-bbd1-87f7c8b98e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df91583d-4b9c-47d9-99ed-a1d5e7032c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kios_nama&quot;)</value>
      <webElementGuid>dcd34735-2713-4c7b-840c-22ba53e66185</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kios_nama']</value>
      <webElementGuid>edabf1d1-c676-4378-ba50-2ce629e7fd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='tambah-kios']/div/div/div/input</value>
      <webElementGuid>d3467539-6396-4d3a-bb66-60a20449fda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/input</value>
      <webElementGuid>d991365f-3410-41b9-8245-80555cb270d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'kios_nama' and @name = 'kios_nama' and @placeholder = 'Tulis Nama Kios' and @type = 'text']</value>
      <webElementGuid>e263a412-9a39-4f1f-9ae9-22993cdf1d8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
