<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__akhiran</name>
   <tag></tag>
   <elementGuidId>5376c473-cfff-4dd2-ae87-652113e0e902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='akhiran']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#akhiran</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e14ef43e-439b-4a32-8a8d-2e572a53408f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>akhiran</value>
      <webElementGuid>8b305345-0cce-4fec-b673-147d2dda13dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>akhiran</value>
      <webElementGuid>8b9ca405-9d21-4fb5-861e-e9e0acd642f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>32c5c837-4dbf-45e0-8ea7-4587601d853b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>TBK</value>
      <webElementGuid>a1c83c86-e62f-441f-abbb-3c50834a95ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b67c8b62-6812-40f7-a032-719e6b311669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;akhiran&quot;)</value>
      <webElementGuid>bfb71f79-e2ac-451f-8814-160428cf2b8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='akhiran']</value>
      <webElementGuid>c5345a08-132f-4cb0-a1e3-6768c7f8b079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-dealer']/div[3]/div/div[4]/div/input</value>
      <webElementGuid>8512c759-4a0b-42e6-8786-e58d0d55548d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>76c83c73-a25d-4b52-a252-65eaa279c565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'akhiran' and @name = 'akhiran' and @placeholder = 'TBK' and @type = 'text']</value>
      <webElementGuid>db11cfb2-a7d4-43e9-a670-f068c70de5e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
