<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SIUP</name>
   <tag></tag>
   <elementGuidId>d383f45f-1680-4a44-9e29-bd0ea8f50d79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-attachment_name-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-attachment_name-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb277271-af79-45c1-b3c8-a9fbd198b084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>d5abce5f-9064-495e-9a13-4f1b738dc6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-attachment_name-container</value>
      <webElementGuid>32bab8b4-5bd9-47f0-83f7-e76e2e4fe83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>22845358-a31b-4989-8b46-12187e57a3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ddcf0bd7-e9ff-4c9f-99f4-ad27323dbfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> SIUP </value>
      <webElementGuid>a6493c14-75a1-4a78-94a6-a3b2b9a91a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SIUP </value>
      <webElementGuid>2854f443-f881-4b22-9b67-197b5ee7585b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-attachment_name-container&quot;)</value>
      <webElementGuid>8c4a76a4-769f-4bf0-afe0-30cfc82d978e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-attachment_name-container']</value>
      <webElementGuid>a03dab6f-d6a0-47df-8074-4271304a29f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-lampiran-tokios-dealer']/div/div/span/span/span/span</value>
      <webElementGuid>a169bc84-ce95-44c1-ada2-c96ab694bc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran berhasil diupload !!!'])[1]/following::span[4]</value>
      <webElementGuid>f8489717-ca8c-4378-9684-a059f00ea5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran Pengajuan Sub-Dealer'])[1]/following::span[4]</value>
      <webElementGuid>5b166de7-9e75-4cdf-a1ca-d1f394ff9067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lain-lain'])[1]/preceding::span[3]</value>
      <webElementGuid>365b8d07-d2ed-4c7d-a7d4-9e7384ede2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>feaace0b-c266-4041-bd66-2ae63136ce61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-attachment_name-container' and @title = ' SIUP ' and (text() = ' SIUP ' or . = ' SIUP ')]</value>
      <webElementGuid>8bb208ae-21d6-4f3d-a67a-c53b74084a56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
