<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KTP</name>
   <tag></tag>
   <elementGuidId>f85eaf36-958f-4ec1-b56d-4d993fc12c7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-attachment_name-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-attachment_name-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0342643f-2c08-4736-a69a-403251e15d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>d4b0b0f0-9279-405a-a1d6-55b8df4306d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-attachment_name-container</value>
      <webElementGuid>370e2e01-13ec-4be5-bca2-5e3125bc857e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1e3ec8ba-954a-4935-b5cd-10fba5946ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d5e24a1-2db1-45ac-931a-3eedb967fd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> KTP </value>
      <webElementGuid>886f2f8c-f0a0-4842-8839-e3ddaa60cd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> KTP </value>
      <webElementGuid>2800b922-8799-4f94-9ee7-b6a10e8b978a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-attachment_name-container&quot;)</value>
      <webElementGuid>b0f5c2d8-a83e-409f-94be-fb697339ad35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-attachment_name-container']</value>
      <webElementGuid>e9a897b6-4fb2-46fa-b0be-a756c547c03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-lampiran-tokios-dealer']/div/div/span/span/span/span</value>
      <webElementGuid>4897e351-082d-41e4-b359-a40a13bd52df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran berhasil diupload !!!'])[1]/following::span[4]</value>
      <webElementGuid>c0c36bf3-36cf-4c8b-a636-c3495ed134cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran Pengajuan Sub-Dealer'])[1]/following::span[4]</value>
      <webElementGuid>74bbdcd1-75a3-4a36-9d55-cce2478211bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lain-lain'])[1]/preceding::span[3]</value>
      <webElementGuid>92554f2d-0bce-4aa0-a0b9-3f29c5409185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[41]/preceding::span[3]</value>
      <webElementGuid>daaa4b9a-b4c2-4721-a486-8f24535e46b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>178646fe-283a-4a32-8efd-e5c9f72d1e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-attachment_name-container' and @title = ' KTP ' and (text() = ' KTP ' or . = ' KTP ')]</value>
      <webElementGuid>5ee4b163-588f-4436-869e-bee01164ef32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
