<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Foto Sub-Dealer (WAJIB)</name>
   <tag></tag>
   <elementGuidId>05d843d1-cd0f-4a9b-a1c1-d2a656051310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-attachment_name-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-attachment_name-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f654a2d2-11b5-4013-8d97-2ba28c1a68c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>db6e074a-d4cd-4eee-b3f0-a63fab0e01a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-attachment_name-container</value>
      <webElementGuid>f66d8807-fc50-4615-8acf-73208293fdbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2f229750-0f07-4e29-b043-9a1102d801e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>453dbc26-4cf7-44c7-8feb-9c2a7285ea2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Foto Sub-Dealer (WAJIB)</value>
      <webElementGuid>510fdf83-308a-4ae8-8af9-c34ff38a06e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Foto Sub-Dealer (WAJIB)</value>
      <webElementGuid>a526c308-cb12-4855-ab52-7093e0560edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-attachment_name-container&quot;)</value>
      <webElementGuid>4e74eb15-b591-4147-977b-ad6a6ecb2da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-attachment_name-container']</value>
      <webElementGuid>be9dcd54-641b-4b68-b008-8096b67b673e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-lampiran-tokios-dealer']/div/div/span/span/span/span</value>
      <webElementGuid>e9fb5ecd-d6a7-41fc-b5c5-67d3097117e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran berhasil diupload !!!'])[1]/following::span[4]</value>
      <webElementGuid>0690cc2b-aba1-4723-a171-1f5f47d573c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran Pengajuan Sub-Dealer'])[1]/following::span[4]</value>
      <webElementGuid>5acfe218-1d76-41ae-b8dc-cfb3ec01cdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lain-lain'])[1]/preceding::span[3]</value>
      <webElementGuid>8daaafcb-4bf6-47e0-a867-6139c4da61bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[41]/preceding::span[3]</value>
      <webElementGuid>7b1c9ade-9448-442b-865d-ef60b8d3a4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>301e6312-94f9-428e-9b98-f3f9e807bd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-attachment_name-container' and @title = ' Foto Sub-Dealer (WAJIB)' and (text() = ' Foto Sub-Dealer (WAJIB)' or . = ' Foto Sub-Dealer (WAJIB)')]</value>
      <webElementGuid>20f61c1d-47ed-41a5-88da-c6ac7d4531a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
