<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Distributor</name>
   <tag></tag>
   <elementGuidId>e5f189fb-0142-4389-b79f-ce11adf92ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-distribotor-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-distribotor-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b350b59c-0121-47da-9d5d-788a1dfdb887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>f405f557-f6d9-4a6c-9cc5-43523d28a3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-distribotor-container</value>
      <webElementGuid>c141407d-cf9d-4c48-b53a-7350380d4c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>80c5917d-cf3d-49a3-be32-0cf024b005a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bbe5f0e4-e182-4f1a-a60a-441e04d57195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Pilih Distributor </value>
      <webElementGuid>1d0f31be-ea11-4b0e-ab0e-335a7118437c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih Distributor </value>
      <webElementGuid>adfe573c-f692-433b-b001-2d50077bc36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-distribotor-container&quot;)</value>
      <webElementGuid>50d3c7ef-279f-4203-a6bf-a062503dc2e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-distribotor-container']</value>
      <webElementGuid>f843409a-9951-4feb-8358-7c57ce1e5df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-dealer']/div[10]/span/span/span/span</value>
      <webElementGuid>2d9ceda8-b15a-42fc-aa5d-535b121c5da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distributor'])[1]/following::span[4]</value>
      <webElementGuid>3f13c15e-9807-4cfe-9372-02f6b5ab871e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/following::span[4]</value>
      <webElementGuid>aece875f-18b3-4811-95b4-4aea86be9fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrasikan'])[1]/preceding::span[3]</value>
      <webElementGuid>d86d2bbd-d7f6-41f7-be01-5f615bb0924a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Lampiran'])[2]/preceding::span[3]</value>
      <webElementGuid>41cf45c0-a1c4-47b9-863f-bb81683733e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/span/span/span/span</value>
      <webElementGuid>84a366e5-acfa-4910-95c3-b3ef49da0166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-distribotor-container' and @title = ' Pilih Distributor ' and (text() = ' Pilih Distributor ' or . = ' Pilih Distributor ')]</value>
      <webElementGuid>49bc76b6-89ee-4812-9287-35a7febaeb34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
