<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Jenis Entitas</name>
   <tag></tag>
   <elementGuidId>10050b16-ddd6-4e60-b6b4-4a54938ff3de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-entity_id-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-entity_id-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a3084a73-2c65-4d27-8e47-29b04ac9d371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>d1bf1bf8-d50c-4f9d-9f67-88952d2680e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-entity_id-container</value>
      <webElementGuid>3521193d-df2a-49e1-bfec-0859c64cc85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>5d958e3f-ec40-4605-b938-62028cf27a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a07d95a1-f2e2-4dca-89e5-e204f0dc8781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Pilih Jenis Entitas </value>
      <webElementGuid>82ee32e2-8096-4145-b023-1598d1d319f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih Jenis Entitas </value>
      <webElementGuid>b7c9df55-5651-4a3a-a295-eb6120896cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-entity_id-container&quot;)</value>
      <webElementGuid>37449877-57e5-4768-b370-c5172b354800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-entity_id-container']</value>
      <webElementGuid>72038ae8-a6d6-4f55-9d11-094a39629767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-dealer']/div[2]/span/span/span/span</value>
      <webElementGuid>52feb913-2121-413f-8c4e-4244cc516a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::span[4]</value>
      <webElementGuid>294c08a3-079b-458b-9e0c-ff37ee993244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::span[3]</value>
      <webElementGuid>9d88fda1-0b0f-409a-b7dd-e192229ae9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>e58d1bcd-2208-4b0e-a72a-b5c5d7c3843b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-entity_id-container' and @title = ' Pilih Jenis Entitas ' and (text() = ' Pilih Jenis Entitas ' or . = ' Pilih Jenis Entitas ')]</value>
      <webElementGuid>a3defb7d-1c14-4448-921c-39252587fd55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
