<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Lampiran</name>
   <tag></tag>
   <elementGuidId>0504e733-e395-4643-9606-43ed1c54892e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-attachment_name-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-attachment_name-container']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'select2-attachment_name-container' and @title = ' Pilih Lampiran ' and (text() = ' Pilih Lampiran ' or . = ' Pilih Lampiran ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bdbc4172-eb9b-42e5-a204-46e763e397b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>366bfc40-65f3-4ac2-bfd8-348833b3b697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-attachment_name-container</value>
      <webElementGuid>aa5ebf6e-22ff-4477-b2ee-89a7d508313a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a5c42b3a-f204-4862-8cd7-9162a024db7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e9544976-31e5-410b-b973-b1c61b55d36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Pilih Lampiran </value>
      <webElementGuid>ad1335b8-7d1b-4f36-afcd-ba017f2287dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih Lampiran </value>
      <webElementGuid>fe8583b0-f8ae-4b88-acf8-2c6875c1f303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-attachment_name-container&quot;)</value>
      <webElementGuid>0e288adb-0233-4c2f-963d-34c0c19e4449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-attachment_name-container']</value>
      <webElementGuid>b3a565e4-6614-49af-a2cc-c25ca42bd745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-lampiran-tokios-dealer']/div/div/span/span/span/span</value>
      <webElementGuid>d24f1a01-b711-472b-a703-f608ec969162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran Pengajuan Sub-Dealer'])[1]/following::span[4]</value>
      <webElementGuid>bb3af2b7-9554-43c9-a5e9-7afc882b60b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lain-lain'])[1]/preceding::span[3]</value>
      <webElementGuid>7ec001f3-c5af-47ce-9e4b-fb96ae5a9ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[41]/preceding::span[3]</value>
      <webElementGuid>e9b793da-efc7-4e55-b7ec-e495d4763499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>c884dcea-cb85-43a4-8afe-83168deef3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-attachment_name-container' and @title = ' Pilih Lampiran ' and (text() = ' Pilih Lampiran ' or . = ' Pilih Lampiran ')]</value>
      <webElementGuid>0b27779e-3ea6-4e5a-bfe9-9a1a98e30965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Sukses Diupload'])[1]/following::span[4]</value>
      <webElementGuid>4a5c6fa5-b477-481a-ba34-281725aca8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran Pengajuan Dealer'])[1]/following::span[5]</value>
      <webElementGuid>9eef0627-dd55-49b8-b02f-8867b1a2d7f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
