<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Kecamatan - personelRMC</name>
   <tag></tag>
   <elementGuidId>d08ad0b6-26db-4146-9fb5-7acfd0bfbc95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[52]/div/main/div/div/div[1]/div[1]/div/div/div[2]/form/fieldset/div[1]/div[2]/div[3]/span/span[1]/span/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-owner_kecamatan-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7bc830ad-24c8-4dc7-8f69-f5cb2bdd4b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>97a89949-c2f3-4063-841e-b91ddd292933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-owner_kecamatan-container</value>
      <webElementGuid>93e22ae5-cfb3-4554-a204-481ec60daf1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b49a9bd4-e65d-47a1-81b6-ce29216021b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d046cc0-0306-46a7-a89d-49bfe7ee5515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Pilih Kecamatan </value>
      <webElementGuid>45ee3f1e-22d7-4731-adb5-9b39aeed9c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih Kecamatan </value>
      <webElementGuid>ec51b023-5532-4e0f-a10d-5308e409d70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-owner_kecamatan-container&quot;)</value>
      <webElementGuid>1e5c8286-40b2-481f-aff5-b635675f6458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-owner_kecamatan-container']</value>
      <webElementGuid>f8272ba3-f218-4e53-8e1f-0e104e2c4708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-pemilik']/div[6]/span/span/span/span</value>
      <webElementGuid>4af70b55-7f28-416b-9861-ba6210490b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[4]</value>
      <webElementGuid>2cc2c0d5-0c62-4854-a173-c623af7affe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::span[3]</value>
      <webElementGuid>8f2267dc-fb45-48c9-a95d-2b9909ec125c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/span/span/span</value>
      <webElementGuid>f1306aac-3e03-44f4-94a1-140b1c5b8bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-owner_kecamatan-container' and @title = ' Pilih Kecamatan ' and (text() = ' Pilih Kecamatan ' or . = ' Pilih Kecamatan ')]</value>
      <webElementGuid>523a0a81-3b0b-498e-ac07-6ce6475242ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-kios_kecamatan-container']</value>
      <webElementGuid>13edafe9-e36b-40ec-90b8-995da4f23180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='tambah-kios']/div/div[2]/div[3]/span/span/span/span</value>
      <webElementGuid>a950dfe1-d345-4367-93d3-f7bc5c61413f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::span[4]</value>
      <webElementGuid>f54ede63-0214-4faf-946f-812c4885ecde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Harus pilih kecamatan!'])[1]/preceding::span[3]</value>
      <webElementGuid>54616be2-b6a2-472b-8a0d-53b38adefe7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span</value>
      <webElementGuid>0e5bee2b-8065-4ec5-80e3-49a62dde6ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-kios_kecamatan-container' and @title = ' Pilih Kecamatan ' and (text() = ' Pilih Kecamatan ' or . = ' Pilih Kecamatan ')]</value>
      <webElementGuid>6f2e2094-2338-4045-944b-427b1a433130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
