<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Identitas Dealer</name>
   <tag></tag>
   <elementGuidId>ea387303-7897-41a7-b743-2ebf1711d17a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='identitas-dealer']/div/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#identitas-dealer > div.form-header > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>55e65da4-50d5-4e18-9661-74ab8b2ede80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Identitas Dealer </value>
      <webElementGuid>361276fb-6914-4a34-8b5d-5e365457799c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identitas-dealer&quot;)/div[@class=&quot;form-header&quot;]/strong[1]</value>
      <webElementGuid>d76bd45e-7469-4130-9b26-d4a53caf6038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identitas-dealer']/div/strong</value>
      <webElementGuid>8363b268-94e4-44d9-a1be-50c814f74510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atas Nama'])[1]/following::strong[1]</value>
      <webElementGuid>ed126d31-85d9-432f-b49b-ec952692bade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Rekening'])[1]/following::strong[1]</value>
      <webElementGuid>f330363f-d6fd-4dcb-9339-03ed28cd6b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::strong[1]</value>
      <webElementGuid>9e23ee80-3d27-4834-bd84-1b58606d8dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Identitas Dealer']/parent::*</value>
      <webElementGuid>f46b14e0-231a-40fe-a93b-4bb978ef32c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/strong</value>
      <webElementGuid>79226a5b-2063-4baf-b0b9-a021d1409679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = ' Identitas Dealer ' or . = ' Identitas Dealer ')]</value>
      <webElementGuid>4c3f42df-cfc6-43c5-91ba-c10028f653c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
