<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Setujui</name>
   <tag></tag>
   <elementGuidId>d6b29c1e-3cee-47e5-952b-30e1c15fc42d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[99]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.button-setuju</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f97a8dbe-885c-47ad-b1c7-f19dcc63bf69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53a3109c-f99b-42cc-81c7-5f22b62d0757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-setuju</value>
      <webElementGuid>315fc67f-bca3-439e-abd4-5cc92ee38ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Setujui
                            </value>
      <webElementGuid>b07c98a0-9750-4ce1-bb4e-eeeecb3ea1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-konfirmasi-kios&quot;)/div[@class=&quot;modal-table-petani&quot;]/button[@class=&quot;btn button-setuju&quot;]</value>
      <webElementGuid>a38e9202-7c95-4267-8719-d0bcfd4465e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[99]</value>
      <webElementGuid>e0fa5463-b2a4-41f0-97e8-ebcc535affac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-konfirmasi-kios']/div/button</value>
      <webElementGuid>d401ba66-0123-4db0-af74-c97cd0f95094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan Jika Ditolak'])[1]/following::button[1]</value>
      <webElementGuid>4f33761a-65be-4770-b4f2-73a1cafc4706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berbah Sleman YK'])[1]/following::button[1]</value>
      <webElementGuid>355e3179-5abd-4a33-8b32-bb85965b472e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda sudah yakin dengan data tersebut?'])[8]/preceding::button[1]</value>
      <webElementGuid>7e39d89e-b02a-401e-8862-88c6cc86dcbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[41]/preceding::button[1]</value>
      <webElementGuid>bcbe8a1a-f2e4-4bad-9669-69c593f23249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Setujui']/parent::*</value>
      <webElementGuid>681955ba-cc17-476d-a544-24560165acdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>cde1c1ce-90e7-4cc6-a873-9563bece537f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                Setujui
                            ' or . = '
                                Setujui
                            ')]</value>
      <webElementGuid>351d1d26-9ba4-4cf2-b7af-f8629a0800df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
