<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ya</name>
   <tag></tag>
   <elementGuidId>8edc6aa3-42a6-4a29-904c-507962225a1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='SubmitButtonKios']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmitButtonKios</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4606ffca-365d-4be0-91a4-4e19d4cf1055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>214ef861-bae3-4c6b-80c7-0f162ee84f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-modal</value>
      <webElementGuid>642796db-8e39-4f9c-8403-411f48bfcd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmitButtonKios</value>
      <webElementGuid>d38c46f0-2af6-4e39-af55-0fbdaae17bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>9f28adc4-5ae3-4d21-9b25-4ebf2804ff15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>527cb592-6fdb-45d7-8972-48b4fa3721bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ya </value>
      <webElementGuid>e5985474-296c-4a99-b9a7-2c8f5ae32e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;c-app modal-open&quot;]/div[@id=&quot;modal-add-kios&quot;]/div[@class=&quot;modal-dialog modal-confirmation&quot;]/div[@class=&quot;modal-content add&quot;]/div[@class=&quot;modal-footer&quot;]/button[@id=&quot;SubmitButtonKios&quot;]</value>
      <webElementGuid>6639caeb-eb14-4d7a-83ff-5fef1aa36ae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='SubmitButtonKios']</value>
      <webElementGuid>61517960-a76a-4af0-9e60-215fa34822d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-add-kios']/div/div/div[2]/button[2]</value>
      <webElementGuid>45bfb71c-4ef3-4fad-abed-f39f14887f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[5]/following::button[1]</value>
      <webElementGuid>5aaf94f7-3bad-4284-ade1-d767200d205a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MENYETUJUI'])[3]/following::button[2]</value>
      <webElementGuid>2883a00b-136c-45ea-800a-dd656fcbfa99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[6]/preceding::button[1]</value>
      <webElementGuid>d586b677-f702-41a1-b299-b7893291dbc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[6]/preceding::button[2]</value>
      <webElementGuid>db62963e-0d3f-4914-a6a7-e0bf252335be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/button[2]</value>
      <webElementGuid>6d001616-f8ce-4f15-a76a-c5fce63b8932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'SubmitButtonKios' and (text() = ' Ya ' or . = ' Ya ')]</value>
      <webElementGuid>9a2322c3-6cb2-4ae1-8548-01d12558d378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
