<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail</name>
   <tag></tag>
   <elementGuidId>edcca1ed-6cf9-4a40-97ac-11ac02d2dbf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[99]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58e18f55-dbb7-4d62-83c5-bb559bb6865e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-detail detailclick</value>
      <webElementGuid>a5e9e079-12d1-4edf-ab59-fe1cf0218b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd8539dd-9b7c-4ab5-b0ac-174b614a639c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-detail</name>
      <type>Main</type>
      <value>76d6df80-f634-4d07-801e-2d7c2f95880c</value>
      <webElementGuid>46612332-1d6c-4ea7-97d9-3e89bbb1907f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Detail 
                    </value>
      <webElementGuid>597aba5d-97b9-4f19-8287-7445fec54283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbody-sub-dealer-list&quot;)/tr[2]/td[@class=&quot;text-center align-middle&quot;]/button[@class=&quot;btn button-detail detailclick&quot;]</value>
      <webElementGuid>89055837-2f8c-48f9-842f-f87282f1da4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[99]</value>
      <webElementGuid>df04aa10-d88a-4eee-9a24-afe530eec759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbody-sub-dealer-list']/tr[2]/td[2]/button</value>
      <webElementGuid>1ff9d2ea-afd7-4199-bd83-768325b73a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer'])[2]/following::button[1]</value>
      <webElementGuid>893cb119-6fd5-441d-a00c-45c1522b6235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/preceding::button[1]</value>
      <webElementGuid>51b991b3-62a0-4592-a86a-0b80cacd9dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/button</value>
      <webElementGuid>a4b870ba-4731-4156-ae26-e2deb1772678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                        Detail 
                    ' or . = '
                        Detail 
                    ')]</value>
      <webElementGuid>f16d7e3a-bcbb-4743-85f7-82c088b370ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
