<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ya (1)</name>
   <tag></tag>
   <elementGuidId>46a27e8d-03aa-4182-a7a4-2c3d7f7fafcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ButtonSetujuSubDealer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ButtonSetujuSubDealer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68fce1cc-95dd-474c-ae09-1dce584b555d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e2e52018-3028-4487-8c72-2d81e7404416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-modal</value>
      <webElementGuid>e2df5304-7297-42fb-9ded-43bb1245022d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ButtonSetujuSubDealer</value>
      <webElementGuid>703a29e7-0097-4323-b2f7-51fa1db0d5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>5b9f331c-c3c9-4539-a4d1-6f97ea71ae57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>d8c5999f-0843-4b3f-b679-fbcca03b4980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ya </value>
      <webElementGuid>1d4fd323-8e15-47f7-87e5-368977bd56fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;c-app modal-open&quot;]/div[@id=&quot;modal-add-05&quot;]/div[@class=&quot;modal-dialog modal-confirmation&quot;]/div[@class=&quot;modal-content add&quot;]/div[@class=&quot;modal-footer&quot;]/button[@id=&quot;ButtonSetujuSubDealer&quot;]</value>
      <webElementGuid>3a52c4de-6b65-4a39-a0fe-96207ad3d709</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ButtonSetujuSubDealer']</value>
      <webElementGuid>7991e824-af77-49f1-a0df-3c134aecedd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-add-05']/div/div/div[2]/button[2]</value>
      <webElementGuid>1f73a7ca-0343-4819-bbc5-d7189424023b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[4]/following::button[1]</value>
      <webElementGuid>0dac950c-0d57-4df7-a3cf-c58e2d3a6037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MENYETUJUI'])[2]/following::button[2]</value>
      <webElementGuid>e8d3ebf5-71a1-4564-9f23-7a9123121972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MENYETUJUI'])[3]/preceding::button[1]</value>
      <webElementGuid>b46f32d3-d752-41ef-ab4a-1a9c3cda3e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/button[2]</value>
      <webElementGuid>0e12b37b-e212-477b-9f01-70aa04b145de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'ButtonSetujuSubDealer' and (text() = ' Ya ' or . = ' Ya ')]</value>
      <webElementGuid>295961ed-1aa0-4cf3-8947-fdb18e702729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
