<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Setujui (1)</name>
   <tag></tag>
   <elementGuidId>7631743c-95f0-448f-8743-a9dedc015ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button_confirm_accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_confirm_accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4886ab9e-d1b3-4718-a560-0ec4a14d5465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_confirm_accept</value>
      <webElementGuid>a861467c-a7b7-4b0f-a526-d2f588cfcd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-setuju</value>
      <webElementGuid>5234dd6d-f335-4ecb-a02e-3addd5f6d402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>add8c8d2-c4ec-4717-ba74-3a957d11a1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-add-05</value>
      <webElementGuid>66a984db-b7d8-4912-95ee-d8bcc187d10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>0dd77114-ef08-425a-89bd-9edb49344171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Setujui
                        </value>
      <webElementGuid>8963bf7f-e51f-4437-a619-1064c22828c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_confirm_accept&quot;)</value>
      <webElementGuid>ee71aeb2-60e2-4303-a5f6-fdf14cca3b1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_confirm_accept']</value>
      <webElementGuid>18b083ee-e683-4814-9dce-8ead62346e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-konfirmasi-dealer']/div[2]/div[2]/div[3]/button</value>
      <webElementGuid>5f080c9c-7f15-47c8-aa34-3b98497ce910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::button[1]</value>
      <webElementGuid>b4991972-c064-4354-9f75-7d7d9571aa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan Jika Ditolak'])[1]/following::button[2]</value>
      <webElementGuid>0124df0c-f612-48d8-b85f-ec6173f1e632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda sudah yakin dengan data tersebut?'])[8]/preceding::button[1]</value>
      <webElementGuid>89b5cd7d-2392-450a-b07b-fe102a6ba3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[41]/preceding::button[1]</value>
      <webElementGuid>e509f0f2-f098-4472-8f90-c8b52ee6c68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Setujui']/parent::*</value>
      <webElementGuid>64e68893-afbe-4734-b541-bc32760d4365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/button</value>
      <webElementGuid>ed8d7b50-1b51-41ca-a9b5-c94cd252315d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button_confirm_accept' and @type = 'button' and (text() = '
                            Setujui
                        ' or . = '
                            Setujui
                        ')]</value>
      <webElementGuid>1c3611a1-659a-4b0b-a7b9-5ab5e22a955f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
