<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Konfirmasi</name>
   <tag></tag>
   <elementGuidId>2522bcd2-9238-4e94-8fa8-9a7d4750f43a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tbody_stores_table']/tr/td[6]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-table-konfirmasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92cdb0bb-2e0e-4690-a0e8-a521a515cc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-table-konfirmasi</value>
      <webElementGuid>a57576ab-184a-4c1f-896e-584526feb2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>0d3390f0-3083-4e1b-b3e7-7067ae18a0f0</value>
      <webElementGuid>8c0669a8-08f6-426b-9c22-df68007075db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>PT.dani yudha aris</value>
      <webElementGuid>b9526ab9-8c42-4c3d-80ca-c2ff73452d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-namemarketing</name>
      <type>Main</type>
      <value>personel RMC untuk tes 1a</value>
      <webElementGuid>c8d56e85-c93b-43c5-8e9c-d5bedfc6788d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-postionmarketing</name>
      <type>Main</type>
      <value>(e907c473-4dac-4356-81b3-a3ebdbbfc5ec)</value>
      <webElementGuid>361e852a-69ae-4df3-a5b4-7f3a1f2caa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-telephone</name>
      <type>Main</type>
      <value>123456789</value>
      <webElementGuid>e12c58c8-7a87-45ca-b673-b9abc9b28bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-address</name>
      <type>Main</type>
      <value>Jalan damai jakal</value>
      <webElementGuid>2681658d-b7f8-4623-a783-dd898a6b4585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-province</name>
      <type>Main</type>
      <value>94</value>
      <webElementGuid>94490d06-18c8-4de4-a293-8b01ab503ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-city</name>
      <type>Main</type>
      <value>9436</value>
      <webElementGuid>79b7f115-48ad-440b-bd2b-8955b2d3fb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-district</name>
      <type>Main</type>
      <value>9436030</value>
      <webElementGuid>f00d6143-a3f8-4d48-bc59-b164021a516f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gmaps</name>
      <type>Main</type>
      <value>https://www.google.co.id/maps/@-7.7094418,110.4109991,14z</value>
      <webElementGuid>b20128d7-0d1e-45ca-9703-d5980030a90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>filed</value>
      <webElementGuid>7f63d645-f82a-4487-94f1-45be873455d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Konfirmasi
                                    </value>
      <webElementGuid>f3ecc915-535d-4256-9953-6cb65a5c7af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbody_stores_table&quot;)/tr[1]/td[6]/button[@class=&quot;btn btn-sm btn-table-konfirmasi&quot;]</value>
      <webElementGuid>be886e83-ec02-4ae6-97b6-358f415c579e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbody_stores_table']/tr/td[6]/button</value>
      <webElementGuid>5b96efcd-e228-4c08-a1cf-40b325674b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan Baru'])[1]/following::button[1]</value>
      <webElementGuid>b2148189-1d9f-4347-a856-56863504ca75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAC Sub-Region 1a'])[1]/following::button[1]</value>
      <webElementGuid>fbe6cf7a-175f-44d3-bd42-9c9879b2d84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT.dani yudha aris'])[2]/preceding::button[1]</value>
      <webElementGuid>2b754380-9b97-476f-b090-30344761f671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/button</value>
      <webElementGuid>fb9d03cd-5705-481d-8c8a-0bff443dce0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                                        Konfirmasi
                                    ' or . = '
                                        Konfirmasi
                                    ')]</value>
      <webElementGuid>7dab91f0-28e3-41ab-a93e-b59b7cf9b62d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
