<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PT CERIA SEJAHTERA_btn btn-sm btn-tab_2dcee3</name>
   <tag></tag>
   <elementGuidId>87914ab6-ae94-4aa7-8749-3d89c207cdfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-sm.btn-table-konfirmasi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Konfirmasi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72b73b29-872c-4776-9acb-8d5b96d69867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-table-konfirmasi</value>
      <webElementGuid>955f6fed-9412-471c-99c2-355d5492c7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b3a8d733-cf4d-4fb9-9e74-8554fe5d0ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>ad08c85f-e849-4a26-abae-45d5cf1f7b7a</value>
      <webElementGuid>44025420-3113-4c64-b23f-acb658e51dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>PT CERIA SEJAHTERA</value>
      <webElementGuid>2163df6d-d734-4dc2-9f7b-c38cb36d7190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sub-submission</name>
      <type>Main</type>
      <value>Pengajuan Baru</value>
      <webElementGuid>5f27a31f-8c48-42ad-855c-02d8994abfae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-telephone</name>
      <type>Main</type>
      <value>11234567890</value>
      <webElementGuid>0124e2f4-d937-4ece-a102-ce1c4e8000b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gmaps_link</name>
      <type>Main</type>
      <value>https://www.google.co.id/maps/@-7.7094418,110.4109991,14z</value>
      <webElementGuid>39c258e7-2d13-4fff-84fe-6bb88d842422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-owner</name>
      <type>Main</type>
      <value>Sung-ha-Jung</value>
      <webElementGuid>86b3901f-3203-4681-acaa-edfce6d2777e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-owner_telephone</name>
      <type>Main</type>
      <value>81234567890</value>
      <webElementGuid>ceb9c9ef-5c89-44e6-804c-0ac1e50a7654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-owner_npwp</name>
      <type>Main</type>
      <value>12.345.678.9-000.000</value>
      <webElementGuid>63770a46-eeef-4623-8f4d-bb02b06cf661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-owner_ktp</name>
      <type>Main</type>
      <value>123456789000000</value>
      <webElementGuid>439a09e7-205d-4921-bbaa-38fd7f68778a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-owner_address</name>
      <type>Main</type>
      <value>mantijeron,deiyai, Papua</value>
      <webElementGuid>32e65ff7-7c4e-4d87-89fe-bba44d19ce2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-address</name>
      <type>Main</type>
      <value>Jalan ceria atas</value>
      <webElementGuid>3f5b9c77-748b-4786-b9c6-afc53a0072e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>filed</value>
      <webElementGuid>617ac4d4-0aef-4010-be2d-6ca00f242419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-personel</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>5cb23611-a2b2-4982-af63-5b647fed1327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dealer_district</name>
      <type>Main</type>
      <value>Tigi</value>
      <webElementGuid>3c53e9d9-77e0-4f02-9d78-b13f5f0325a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dealer_district_id</name>
      <type>Main</type>
      <value>9436030</value>
      <webElementGuid>8f4d57d6-71e6-4a57-bba4-36c1a3d7c1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dealer_city</name>
      <type>Main</type>
      <value>Kabupaten Deiyai</value>
      <webElementGuid>1a5b3176-1ae4-4c14-923b-8b87fc2cdd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dealer_city_id</name>
      <type>Main</type>
      <value>9436</value>
      <webElementGuid>f6a8069f-7066-4fe0-b09b-c4f25fc29a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dealer_province</name>
      <type>Main</type>
      <value>Papua</value>
      <webElementGuid>8d20db28-4a0f-479b-b306-6147a24b2fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dealer_province_id</name>
      <type>Main</type>
      <value>94</value>
      <webElementGuid>43c6bc4d-1957-4bc2-8b6e-6339ff0f6743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-subregion</name>
      <type>Main</type>
      <value>RAC Sub-Region 1a</value>
      <webElementGuid>efcc37f7-f2dd-4504-bab5-76e9bfc16351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-region</name>
      <type>Main</type>
      <value>RAC region 1</value>
      <webElementGuid>cdacb567-b6cf-497f-a8f6-d1dde8855c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-owner_district</name>
      <type>Main</type>
      <value>Kinal</value>
      <webElementGuid>712bb48e-905e-4bd7-aa51-e4ae17e956ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-owner_city</name>
      <type>Main</type>
      <value>Kabupaten Kaur</value>
      <webElementGuid>f83bcdfb-0600-4acf-b47c-00fbee6e8eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-owner_province</name>
      <type>Main</type>
      <value>Bengkulu</value>
      <webElementGuid>9ad04be9-9624-403a-ba09-4f8eae6ac0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Konfirmasi</value>
      <webElementGuid>0822ce61-67db-4658-9ace-ca55984d8301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbody-sub-dealer-confirmation&quot;)/tr[1]/td[@class=&quot;text-center align-middle&quot;]/input[@class=&quot;btn btn-sm btn-table-konfirmasi&quot;]</value>
      <webElementGuid>812d3c66-e1c3-4b18-aa42-bde24789b2fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Konfirmasi']</value>
      <webElementGuid>395c00ce-8a86-46d5-9cbd-19484da9231b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbody-sub-dealer-confirmation']/tr/td[7]/input</value>
      <webElementGuid>c66f2d29-a458-464f-85da-d3474b507c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>8ba70939-4b42-4e6d-904b-953cb9396016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>a56f9032-fd72-4a80-89b5-65ec2e840940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
