<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KTP_form-check-input</name>
   <tag></tag>
   <elementGuidId>bf53a26d-c1d8-4e38-b1fc-db92df4e2caa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-check.check-konfirmasi > input.form-check-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>927c5069-1c08-4b57-98cb-3af043c17e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>val</name>
      <type>Main</type>
      <value>KTP</value>
      <webElementGuid>21a6ea14-ce30-4a26-b2d7-b389fe06aba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c97613a4-168d-48b4-b01a-bb15930d8ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>86136e76-211b-4e17-bc64-539383ec6848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dealerFileList&quot;)/tbody[1]/tr[1]/td[4]/div[@class=&quot;form-check check-konfirmasi&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>4bb1722b-328d-405f-a0a0-34956ac42dee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>aaae3be8-5179-4e16-bd6a-37e1838a935a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dealerFileList']/tbody/tr/td[4]/div/input</value>
      <webElementGuid>b30be3d6-b326-463a-81a8-ffe26f42f9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>ad4dae5f-4080-4175-9028-ef3fd1ebae9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>bf885496-580f-4c7a-b61d-cdae33b8fa25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
