<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter_nameKios</name>
   <tag></tag>
   <elementGuidId>25ecf24c-2fa8-4618-ba94-ef1f5ebd5225</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchKonfirmasiKios']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchKonfirmasiKios</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a4b68de-40cf-4da2-a016-ffdfd8f2ff20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b0bd9ba-ce23-480b-a01b-321fd8a44af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input-icon</value>
      <webElementGuid>75c432f1-58f0-4861-ab72-909fe92191cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchKonfirmasiKios</value>
      <webElementGuid>c525025d-da76-4900-9ac8-8707ed038482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Kios</value>
      <webElementGuid>0dc2d11a-cadf-49c5-85a9-bdad6a8aa8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameKios</value>
      <webElementGuid>7206ef67-1b2e-4e07-beb5-ce757ae88594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>59f967ab-b5d8-4e75-bc21-cf2e097b0727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return event.key != 'Enter';</value>
      <webElementGuid>d69e466c-fa7c-4d9e-bcf3-0bd84aa8fc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchKonfirmasiKios&quot;)</value>
      <webElementGuid>f0dec232-4a8d-4e39-b66e-335d74175cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchKonfirmasiKios']</value>
      <webElementGuid>a64a5c66-6db9-47d2-9324-1eea14d789f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store_search_formkoios-delegete']/div/div/div/input</value>
      <webElementGuid>7a845811-032b-41fa-953a-c47978897d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>c6731078-4dee-4ce4-a4be-bc405ed3c489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'searchKonfirmasiKios' and @placeholder = 'Cari Kios' and @name = 'nameKios']</value>
      <webElementGuid>a0d09773-fb09-4fd1-b0c3-20dc7873efd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
