<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter_searchAll</name>
   <tag></tag>
   <elementGuidId>324949b6-2f4a-4465-a21f-ccd7527155ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4afecc02-3fad-4c17-85bc-8bf05738e689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>456c38af-792f-4ecd-8dc2-0a58a6fb7b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input-icon</value>
      <webElementGuid>4ef5b678-8e75-49cc-8359-ad04a1d0eeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchAll</value>
      <webElementGuid>b6044279-d21a-4d79-9a3d-a1b31706adad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Pemilik/Sub-Dealer</value>
      <webElementGuid>41f001f2-ab58-41d1-9dd8-547f3707bced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchAll</value>
      <webElementGuid>1ca865d5-1413-4214-8efe-5977b01556a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>506c300e-8ba4-429b-ab16-ecc1b28771bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return event.key != 'Enter';</value>
      <webElementGuid>328caf95-034b-4eff-a0a3-d82548045f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchAll&quot;)</value>
      <webElementGuid>64353a06-3633-4e1e-a4e0-40198b46dd2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchAll']</value>
      <webElementGuid>a84ea2df-dc94-4647-a4ab-c8696a3a0092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='subdealer_search_form']/div/div/div/input</value>
      <webElementGuid>07928b4f-d7d2-47c8-b9af-d1966293fb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>7b359970-fc15-423f-b7ea-2624cee23d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'searchAll' and @placeholder = 'Cari Pemilik/Sub-Dealer' and @name = 'searchAll']</value>
      <webElementGuid>3815eedf-ce05-43d6-b695-81df348fd540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
