<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan Jika Ditolak_confirmation_note</name>
   <tag></tag>
   <elementGuidId>27fcbfdc-e230-4425-9ebe-5e9a09e51ac3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='confirmation_note']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmation_note</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1612968f-6103-4cf5-952e-f25e5480d791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmation_note</value>
      <webElementGuid>c620cc8d-fab8-49a2-94cd-483cd714773e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3acb31d3-2212-4417-a51f-dd804fe7e0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Catatan Penolakan</value>
      <webElementGuid>fe05e09d-ce24-4d0e-93d4-b06f4ebb0f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8e717747-f48d-4068-967b-6cf020bc1ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmation_note&quot;)</value>
      <webElementGuid>827afab0-acfb-4d31-b555-5d8f67f31c28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='confirmation_note']</value>
      <webElementGuid>f31155f5-17d8-4647-b92b-49f402cab31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-konfirmasi-kios']/div/div/textarea</value>
      <webElementGuid>0b045953-054b-4187-a019-6b154ea408f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/textarea</value>
      <webElementGuid>a634c7e6-17ed-4aaa-93ce-9f1134c7f062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'confirmation_note' and @placeholder = 'Catatan Penolakan']</value>
      <webElementGuid>f755b4cf-9c8e-4c7b-8127-9dfc6856ab25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
