<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Marketing</name>
   <tag></tag>
   <elementGuidId>da614f4b-c366-4706-9def-0ef474d1d0f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.landing-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bb4073a9-9b9f-4cc7-8eaf-b1d4a37d9168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>landing-box</value>
      <webElementGuid>a120abed-c485-4b25-8e78-797d6ae34547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>297ba5b6-e5c2-434f-9d21-1743294c4c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                
                                Marketing
                            </value>
      <webElementGuid>b035cac2-b91a-49b1-a48b-1aef087e1990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aa&quot;)/div[@class=&quot;role-box&quot;]/button[@class=&quot;landing-box&quot;]</value>
      <webElementGuid>1692166d-c90b-45c4-a775-479ce1c7498a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>1fe63ab2-60b2-4220-b502-694041e7cbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aa']/div/button</value>
      <webElementGuid>d2289e12-5a90-4cd5-8dc9-37008cd2bc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda akan Masuk Sebagai?'])[1]/following::button[1]</value>
      <webElementGuid>c4284ac4-fa11-491a-9d3a-3fbb5c93624e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat Datang,'])[1]/following::button[1]</value>
      <webElementGuid>d1c1b3be-f0be-49eb-8dcc-fce694f181cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supervisor'])[1]/preceding::button[1]</value>
      <webElementGuid>64efd6a5-8953-410a-abd3-230208cc2260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>652f5dbf-be95-48b5-bdb9-cb92ab0fd1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                
                                Marketing
                            ' or . = '
                                
                                Marketing
                            ')]</value>
      <webElementGuid>90763ba4-ded4-4144-b63a-e297c58cbbd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
