<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>77318e04-af9c-40f8-8290-f6553ed821d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='aa']/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.landing-box > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>12228b4c-aca9-4813-a152-645f12d256f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://fe-staging.kumpulkebon.com/icon/profile_green.svg</value>
      <webElementGuid>41fe9490-4494-4380-89e1-adc3978cf5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aa&quot;)/div[@class=&quot;role-box&quot;]/button[@class=&quot;landing-box&quot;]/img[1]</value>
      <webElementGuid>7107ef01-8026-4a3a-aaf7-d86818dbbf35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aa']/div/button/img</value>
      <webElementGuid>c7628a37-c686-4bcc-aff3-127558e77c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://fe-staging.kumpulkebon.com/icon/profile_green.svg')]</value>
      <webElementGuid>488b5bdd-0a7b-4c3e-bfd5-e0f7e535c3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>56349e41-d6d8-43ae-9e60-7933c7f1d0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://fe-staging.kumpulkebon.com/icon/profile_green.svg']</value>
      <webElementGuid>7e15fe8a-ce1f-4090-a712-097f80ff894e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
